In [1]:
import GeoPandas as gps
from sqlalchemy import *
# Connect directly for now until thin interface through Scott's restful service can me created
engine = create_engine('postgresql://kelvin:1234@smalls:9001/thermal')

# Load all the things into memory
sql = "select * from landsat_8_c1"
df = gpd.GeoDataFrame.from_postgis(sql, engine , geom_col='geom').set_index('landsat_scene_id')
df.columns, df.shape

ModuleNotFoundError: No module named 'GeoPandas'

In [2]:
import numpy as np
import numpy.ma as ma
import matplotlib.pyplot as plt
from pylab import rcParams
import plio
from plio.io.io_gdal import GeoDataset as GeoDataSet


/home/cole/miniconda3/envs/thermal/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
#TODO incorporate db, cannot use it off campus while ssh'd so need to address when in the office
def load_dir( band_files ):
    all_bands = []
    all_geodatasets = []
    # could not find a way to add bands to geotiff created with GeoDataSet, thought there was just a function call. Probably mistaken
    for i in range(1, 15):
        if str(i) in band_files:
            band = GeoDataSet(band_files[str(i)])
            all_geodatasets.append(band)
            all_bands.append(band.read_array())
        else:
            all_bands.append( np.empty( shape=(1,1) ) )
    
    return all_bands

In [4]:
data = {'1':'/home/cole/work/data/thermal_stuff/LC08_L1GT_165198_20131110_20170428_01_T2_B1_SensorRad.TIF', '3':'/home/cole/work/data/thermal_stuff/LC08_L1GT_165198_20131110_20170428_01_T2_B3_SensorRad.TIF', '7':'/home/cole/work/data/thermal_stuff/LC08_L1GT_165198_20131110_20170428_01_T2_B7_SensorRad.TIF'}

In [5]:
load_dir( data )

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[5.e-324]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[6.92621784e-310]]),
 array([[6.92621784e-310]]),
 array([[6.92621784e-310]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[6.92621784e-310]]),
 array([[6.92621784e-310]]),
 array([[6.92621784e-310]]),
 array([[6.92